name: Deploy Function App

on:
  [push]
  
env:
  AZURE_FUNCTIONAPP_NAME: catpi-functions
  OUTPUT_PATH: ${{ github.workspace }}/.output
  DOTNET_VERSION: '3.1.x'
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@master
        
      - name: Setup DotNet ${{ env.DOTNET_VERSION }}
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          
      - name: 'Build/Publish'
        run: dotnet publish --configuration Release --output ${{ env.OUTPUT_PATH }}
          
      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: ${{ env.OUTPUT_PATH }}
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
